cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'


urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

club/urls.py
from django.urls import path

from . import views
from .views import ReservationView, ReservationCompleteView, ReservationCancelView

app_name = 'club'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('reservation', ReservationView.as_view(), name='reservation'),
    path('reservation/<int:pk>/', views.ReservationTimeView.as_view(), name='Reservation-times'),
    path('reservation_complete', ReservationCompleteView.as_view(), name='Reservation-complete'),
    path('reservation/cancel', ReservationCancelView.as_view(), name='Reservation-cancel'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('today.urls')),
    path('accounts/', include('accounts.urls')),
    path('photo/', include('photo.urls')),
    path('cart/', include('cart.urls')),
    path('club/', include('club.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

today/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'today'

urlpatterns = [
    path('', studio_home, name='studio_home'),
    path('today/', product_in_category, name='product_all'),
    path('today/<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('today/<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('upload/', ReviewUploadView.as_view(), name='review_upload'),
    path('reveiw/<int:pk>/', DetailView.as_view(model=Review, template_name='today/review.html'), name='review_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class AddProductForm(forms.Form):

    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from today.models import Product
from .forms import AddProductForm
from .cart import Cart


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, is_update=cd['is_update'])
    return redirect('cart:cart_detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def detail(request):
    cart = Cart(request)
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'is_update':True})
    return render(request, 'cart/cart_detail.html', {'cart':cart})

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Shopping cart
{% endblock %}

{% block content %}
<br>
    <div style="text-align: center"><h2>찜 목록</h2></div>
    <br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">예약하기</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="img_thumbnail" style="width: 300px">
                    </a>
                </th>
                <td>{{ product.name }}</td>
                <td><a href="{% url "cart:product_remove" product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td><a href='{% url "club:reservation" %}' class="btn btn-primary">Reservation</a></td>
            </tr>
            {% endwith %}
        {% endfor %}


        </tbody>
    </table>

    <p class="text-right">
        <a href='{% url "today:product_all" %}' class="btn btn-secondary">Continue shopping</a>
    </p>
{% endblock %}