cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'


urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('today.urls')),
    path('accounts/', include('accounts.urls')),
    path('photo/', include('photo.urls')),
    path('cart/', include('cart.urls')),
    path('club/', include('club.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo
from django.conf.urls import url

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/photo_detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    url(r'^photo/(?P<pk>\d+)/comment/$', add_comment_to_photo, name='add_comment_to_photo'),
]

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')

    title = models.CharField(max_length=100, default="제목")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])


class Comment(models.Model):
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='user_comments')
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, null=True, related_name='comments')
    comment_text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.comment_text

    class Meta:
        ordering = ['-id']

photo/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment_text', )

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .forms import CommentForm
from .models import Photo
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def photo_list(request):
    photos = Photo.objects.all()
    paginator = Paginator(photos, 5)
    page = request.GET.get('page')
    try:
        photos = paginator.page(page)
    except PageNotAnInteger:
        photos = paginator.page(1)
    except EmptyPage:
        photos = paginator.page(paginator.num_pages)
    return render(request, 'photo/photo_list.html', {'photos': photos})


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['title', 'photo', 'text']
    template_name = 'photo/photo_upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('photo:photo_list')
        else:
            return self.render_to_response({'form': form})


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['title', 'photo', 'text']
    template_name = 'photo/photo_update.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})


def add_comment_to_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_author = request.user
            comment.photo = photo
            comment.save()
            return redirect('photo:photo_detail', pk=photo.pk)
    else:
        form = CommentForm()
    return render(request, 'photo/add_comment_to_photo.html', {'form': form})

photo/templates/photo/add_comment_to_photo.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h2>댓글 달기</h2>
    <br>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-outline-danger">Send</button>
    </form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <br>
                <br>
                <div class="card">
                    <div class="card-header">
                        <p> 작성자 : {{object.author.username}}</p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> {{object.title|linebreaksbr}} </h5>
                        <p class="card-text"> {{object.text|linebreaksbr}} </p>
                        <p><img src="{{object.photo.url}}" style="width:100%;"></p>
                    </div>
                    <div class="card-footer text-muted">
                        <p> 작성일 : {{object.created}}</p>
                        <p> 수정일 : {{object.updated}}</p>
                    </div>
                </div>
                <br>
                <a class="btn btn-outline-danger btn-sm float-right" href="{% url 'photo:add_comment_to_photo' pk=photo.pk %}" style="margin: 5px;">Add comment</a>
                {% if object.author.id == user.id %}
                <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right" style="margin: 5px;">Update</a>
                {% endif %}
                <br>
                <br>
                <hr>
                {% for comment in photo.comments.all %}
                    <div class="comment">
                        <div class="date">{{ comment.comment_author }} | {{ comment.created_date }}</div>
                        <p>{{ comment.comment_text|linebreaks }}</p>
                    </div>
                {% empty %}
                    <p>No comments here yet :(</p>
                {% endfor %}
                <hr>
                <br>
            </div>
        <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-md-8 panel panel-default">
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}

{% block title %}- List{% endblock %}

{% block content %}

    <br>
    <div style="text-align: center"><h2>QNA</h2></div>

    <div class="btn-group">

</div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default"
                 style="height: 400px">
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">번호</th>
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                        <th scope="col">작성일자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in photos %}
                        <tr>
                            <td> {{ forloop.counter }} </td>
                            <td> <a href="{% url 'photo:photo_detail' pk=post.id %}"> {{ post.title }} </a> </td>
                            <td> {{post.author.username}} </td>
                            <td> {{post.created}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

                {% if photos.has_previous %}
                    <a href="?page={{ photos.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">{{ photos.number }} of {{ photos.paginator.num_pages }}.</span>

                {% if photos.has_next %}
                    <a href="?page={{ photos.next_page_number }}">next</a>
                {% endif %}
                <a href="{% url 'photo:photo_upload' %}" class="btn btn-outline-danger float-right"> 문의하기</a>
            <br>
            <br>
            <div class="col-md-2"></div>
        </div>
     </div>

{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block title %}
- Upate
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <br><br>
        <div class="card">
            <h5 class="card-header" align="right"> 수정하기 </h5>
            <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <br>

            <input type="submit"
                   class="btn btn-outline-danger float-right" value="수정하기">
        </form>
        </div>
        </div>
        <br><br>

    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

photo/templates/photo/photo_upload.html
{% extends 'base.html' %}
{% block title %}
- Upload
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">

        <br><br>
        <div class="card ">
            <h5 class="card-header" align="right"> 글쓰기 </h5>
            <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <br>

            <input type="submit" class="btn btn-outline-danger
            float-right" value="게시하기">
        </form>
        </div>
        </div>
        <br><br>

    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}