cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'


urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

club/urls.py
from django.urls import path

from . import views
from .views import ReservationView, ReservationCompleteView, ReservationCancelView

app_name = 'club'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('reservation', ReservationView.as_view(), name='reservation'),
    path('reservation/<int:pk>/', views.ReservationTimeView.as_view(), name='Reservation-times'),
    path('reservation_complete', ReservationCompleteView.as_view(), name='Reservation-complete'),
    path('reservation/cancel', ReservationCancelView.as_view(), name='Reservation-cancel'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('today.urls')),
    path('accounts/', include('accounts.urls')),
    path('photo/', include('photo.urls')),
    path('cart/', include('cart.urls')),
    path('club/', include('club.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo
from django.conf.urls import url

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/photo_detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    url(r'^photo/(?P<pk>\d+)/comment/$', add_comment_to_photo, name='add_comment_to_photo'),
]

today/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'today'

urlpatterns = [
    path('', studio_home, name='studio_home'),
    path('today/', product_in_category, name='product_all'),
    path('today/<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('today/<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('upload/', ReviewUploadView.as_view(), name='review_upload'),
    path('reveiw/<int:pk>/', DetailView.as_view(model=Review, template_name='today/review.html'), name='review_detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<div id="container">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}

    <title>TODAY,DRAW{% block title %}{% endblock %}</title>
</head>


<body>
    <div class="container">
        <div style="text-align: center">
            <a href="/"><img src="/media/og.jpg" style="width: 30%;"></a>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">오늘을 그리다</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'today:product_all' %}">STUDIO<span class="sr-only">(current)</span></a></li>

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MYPAGE</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'mypage' %}">내정보</a>
                            <a class="dropdown-item" href="{% url 'photo:photo_list' %}">QNA</a>
                            <a class="dropdown-item" href="{% url 'cart:cart_detail' %}">찜</a>
                            <a class="dropdown-item" href="{% url 'club:Reservation-cancel' %}">예약취소</a>
                        </div>
                    </li>
                    <li class="nav-item active"><a class="nav-link" href="{% url 'logout' %}">LOGOUT<span class="sr-only">(current)</span></a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">LOGIN</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">SIGNUP</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        <div class="card text-center">
            <div class="card-header">
                <div class="jumbotron">
                    <h1 class="display-4">TODAY, DRAW</h1>
                    <p class="lead">국내 사진관들의 정보를 한눈에 볼 수 있는 사이트로서, <br> 사진관 예약, 리뷰, 문의를 통해서 원하는 사진관을 찾을 수 있도록 편리함을 제공합니다.</p>
                </div>
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="media/sh.png" class="d-block w-100">
                        </div>
                        <div class="carousel-item">
                            <img src="media/sh.png" class="d-block w-100">
                        </div>
                    </div>

                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <br>
                <br>
                <img src="media/camera.png" style="width: 20%; margin-right:10%;">
                <img src="media/camera.png" style="width: 20%; margin-left:10%;">
                <br>
                <br>
            </div>
        </div>
        {% endblock %}
        {% block pagination %}
        {% endblock %}

        <footer class="footer" style="background-color: #D3D3D3;">
            <p>회사소개 | 이용약관 | 개인정보처리방침 | 제휴/프로모션문의 | 사업자정보 확인<br/>
                Copyright (c) 오늘을 그리다 , All right reserved | 대표이사 : 심지현 | 사업자등록번호 : 10-08-0825 <br/>
                문의전화 : 02-0000-0000 (평일 09:00-18:00, 유료) | 이메일 : moon_info@musicforyou.com | 호스팅서비스사업자 : (주) MOON | © moon Corp.
            </p>
        </footer>
    </div>
</body>
</html>