cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'


urlpatterns = [
    path('', detail, name='cart_detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

club/urls.py
from django.urls import path

from . import views
from .views import ReservationView, ReservationCompleteView, ReservationCancelView

app_name = 'club'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('reservation', ReservationView.as_view(), name='reservation'),
    path('reservation/<int:pk>/', views.ReservationTimeView.as_view(), name='Reservation-times'),
    path('reservation_complete', ReservationCompleteView.as_view(), name='Reservation-complete'),
    path('reservation/cancel', ReservationCancelView.as_view(), name='Reservation-cancel'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('today.urls')),
    path('accounts/', include('accounts.urls')),
    path('photo/', include('photo.urls')),
    path('cart/', include('cart.urls')),
    path('club/', include('club.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

today/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'today'

urlpatterns = [
    path('', studio_home, name='studio_home'),
    path('today/', product_in_category, name='product_all'),
    path('today/<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('today/<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('upload/', ReviewUploadView.as_view(), name='review_upload'),
    path('reveiw/<int:pk>/', DetailView.as_view(model=Review, template_name='today/review.html'), name='review_detail'),
]

today/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)

    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('today:product_in_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)

    price = models.DecimalField(max_digits=10,decimal_places=2)
    stock = models.PositiveIntegerField()

    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        index_together = [['id','slug']]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('today:product_detail', args=[self.id, self.slug])


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)


class Review(models.Model):
    studio = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='studio_review')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_review')

    title = models.CharField(max_length=100, default="")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('today:product_detail', args=[str(self.id)])

today/forms.py
from .models import Review
from django import forms


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('studio','title','photo', 'text')

today/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from club.views import *
from cart.cart import Cart
from cart.forms import AddProductForm
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .forms import *


def studio_home(request):
    return render(request, 'base.html')


def product_in_category(request, category_slug=None):
    cart = Cart(request)
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)

    return render(request, 'today/list.html', {'current_category': current_category, 'categories': categories, 'products': products, 'cart': cart})


class PhotoListView(ListView):
    model = Review
    template_name = 'today/datail.html'
    context_object_name = 'review'


def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm()
    reviews = Review.objects.filter(studio=product)
    return render(request, 'today/detail.html', {'product': product, 'add_to_cart': add_to_cart, 'reviews':reviews})


class ReviewListView(ListView):
    model = Review
    template_name = 'today/datail.html'
    context_object_name = 'review'


class ReviewUploadView(CreateView):
    model = Review
    fields = ['studio','title','photo', 'text']
    template_name = 'today/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})

today/templates/today/detail.html
{% extends 'base.html' %}
{% block title %}Product Detail{% endblock %}
{% block content %}
<br>
    <div class="container" style="margin-bottom: 50px;">
        <div class="row">
            <div class="col-4">
                <img src="{{product.image.url}}" width="100%">
            </div>
            <div class="col">
                <h1 class="display-6" style="color: crimson">{{product.name}}</h1>
                <p><span class="badge badge-secondary">가격</span> {{product.price}} 원</p>
                <p><span class="badge badge-secondary">사진관 설명</span>{{product.description|linebreaks}}</p>
                <br>
                <form action="{% url 'cart:product_add' product.id %}" method="post">
                    {{ add_to_cart }}
                    {% csrf_token %}
                    <input type="submit" class="btb btn-info btn-sm" style="width: 80px" value="찜하기">
                </form>
                <a href="{% url 'club:reservation' %}"><input type="button" class="btb btn-info btn-sm" style="width: 80px" value="예약하기"></a>
                <hr>
            </div>
        </div>
    </div>


    <div class="alert alert-danger"> [ REVIEW ]
    <div class="card" style="margin-top: 20px; margin-bottom: 20px">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default"
                 style="height: 250px">
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                        <th scope="col">작성날짜</th>
                    </tr>
                </thead>
                <tbody>
                {% for post in reviews %}
                    <tr><td> <a href="{% url 'today:review_detail' pk=post.id %}">
                     {{post.title}} </a> </td>
                    <td> {{post.author.username}} </td>
                    <td> {{post.created}} </td>
                    </tr>
                      {% endfor %}
                </tbody>
            </table>
                <a href="{% url 'today:review_upload' %}" class="btn btn-outline-danger float-right"> 리뷰작성</a>

            <br>

            </div>
            <div class="col-md-2"></div>
        </div>
     </div>
    </div>



<br>

{% endblock %}

today/templates/today/list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}
{% block content %}
    <br>
        <div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                     <a class="nav-link {% if not current_category %}active{% endif %}" href="{% url 'today:product_all' %}">All</a>
                </li>
                {% for c in categories %}
            <li class="nav-item">
                 <a class="nav-link {% if current_category.slug == c.slug %}active{% endif %}" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
            {% endfor %}
            </ul>
        </div>

            <br>

                <div class="row">
                <!--어떤 카테고리를 선택하면 그 카테고리에 포함되어 있는 상품들을 표시하는 부분-->
                    {% for product in products %}
                        <div class="col-4" style="width: 600px">
                            <div class="card">
                                {% if product.image %}
                                    <img class="card-img=top" src="{{ product.image.url }}" alt="Product Image" style="height: 200px;">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ product.name }}</h5>
                                    <p class="card-text">{{ product.desription }}<span class="badge badge-secondary">${{ product.price }}</span></p>
                                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">View Detail</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

<br>



{% endblock %}

today/templates/today/review.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
<br>
<br>
<div class="card">
  <div class="card-header">
       <p> 작성자 : {{object.author.username}}</p>
  </div>
  <div class="card-body">
    <h5 class="card-title"> {{object.title|linebreaksbr}} </h5>
    <p class="card-text"> {{object.text|linebreaksbr}} </p>
      <p><img src="{{object.photo.url}}" style="width:100%;"></p>
  </div>
  <div class="card-footer text-muted">
    <p> 작성일 : {{object.created}}</p>
    <p> 수정일 : {{object.updated}}</p>
  </div>
</div>
               
            </div>
            <div class="col-md-2"></div>
            </div>

    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
            </div>
            <div class="col-md-2"></div>
    </div>
{% endblock %}

today/templates/today/upload.html
{% extends 'base.html' %}
{% block title %}
- Upload
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <br><br>
        <div class="card ">
            <h5 class="card-header" align="right"> 리뷰작성 </h5>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {{form.as_p}}
                    {% csrf_token %}
                    <br>
                    <input type="submit" class="btn btn-outline-danger float-right" value="게시하기">
                </form>
            </div>
        </div>
        <br><br>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}